; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27039.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Alex\AppData\Local\Temp\.NETFramework,Version=v4.7.2.AssemblyAttributes.cpp"
